.TH sealsay 1 "27 April 26"

.gcolor blue
.SH NAME
.gcolor
sealsay - A CLI program inspired by cowsay

.gcolor blue
.SH SYNOPSIS
.gcolor
\m[magenta]Bsealsay\m[]
[\m[green]-h\m[]]
[\m[green]-l\m[]]
[\m[green]-r\m[]]
[\m[green]-n\m[]]
[\m[green]-B\m[]]
[\m[green]-R\m[]]
[\m[green]-A\m[]]
[\m[green]-b | -o | -t | -s\m[]]
[\m[green]message ...\m[]]

.gcolor blue
.SH POSITIONAL ARGUMENTS
.gcolor
.TP
\fB\m[green]message\m[]\fP
Text for the seal to say

.gcolor blue
.SH OPTIONS
.gcolor
.TP
\m[green]\fB-h\fP\m[], \m[cyan]\fB--help\fP\m[]
show this help message and exit
.TP
\m[green]\fB-l\fP\m[], \m[cyan]\fB--list\fP\m[]
lists all seals
.TP
\m[green]\fB-r\fP\m[], \m[cyan]\fB--random\fP\m[]
pick a random seal to display your message
.TP
\m[green]\fB-n\fP\m[], \m[cyan]\fB--no-wrap\fP\m[]
disable text wrapping

.gcolor blue
.SH APPEARANCE
.gcolor
.TP
\m[green]\fB-B\fP\m[], \m[cyan]\fB--bold\fP\m[]
makes bubble text bolded
.TP
\m[green]\fB-R\fP\m[], \m[cyan]\fB--rainbow\fP\m[]
makes bubble text rainbow
.TP
\m[green]\fB-A\fP\m[], \m[cyan]\fB--aurora\fP\m[]
makes bubble text aurora'd

.TP SEALS
.TP
\m[green]\fB-b\fP\m[], \m[cyan]\fB--basic\fP\m[]
basic seal
.TP
\m[green]\fB-o\fP\m[], \m[cyan]\fB--old\fP\m[]
old seal
.TP
\m[green]\fB-t\fP\m[], \m[cyan]\fB--triple\fP\m[]
triple seal
.TP
\m[green]\fB-s\fP\m[], \m[cyan]\fB--say\fP\m[]
says something with the og seal

.gcolor blue
.SH EXAMPLE USAGE
.gcolor
sealsay -s 'Hello, world!' # uses the 'basic' seal

sealsay -r Hi              # chooses a random seal

.gcolor blue
.SH AUTHORS
.gcolor
sealsay is written and maintained by Dom (phantypengy) with contritubors cat-forgor (evie)
This Document was written by Matt-PC0 (Matthew Conroy)

.gcolor blue
.SH "SEE ALSO"
.gcolor
cowsay(1)
